services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  #  certbot:
  #    image: certbot/certbot:latest
  #    volumes:
  #      - ./certbot/www/:/var/www/certbot/
  #      - ./certbot/conf/:/etc/letsencrypt/
  #    networks:
  #      - app-network


  rabbitmq:
    image: rabbitmq:3.13.1-management-alpine
    container_name: rabbitmq
    restart: always
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
      - ./.docker/logs/rabbitmq:/var/log/rabbitmq
    networks:
      - app-network

  bucket:
    image: bitnami/minio:2024-debian-12
    container_name: bucket
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_DEFAULT_BUCKETS=${MINIO_DEFAULT_BUCKET}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY={$MINIO_SECRET_KEY}
    volumes:
      - bucket:/bitnami/minio/data
    networks:
      - app-network

  app:
    build:
      context: './'
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    volumes:
      - ./:/var/www
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
volumes:
  rabbitmq-data:
  bucket:
