FROM php:8.3-fpm-alpine

WORKDIR /var/www/backend

# Copy application files
COPY . /var/www/backend

# Install composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Install dependencies
RUN apk add --no-cache \
    libpng-dev \
    libzip-dev \
    postgresql-dev

# Install PHP extensions
RUN docker-php-ext-install pdo pdo_pgsql zip

# Install composer dependencies
RUN composer install

# Clean up
RUN rm -rf /var/cache/apk/*

# Add user
RUN addgroup -g 1000 www && \
    adduser -u 1000 -S www -G www && \
    chown -R www:www /var/www

USER www

EXPOSE 9000
CMD ["php-fpm"]